; Pytest Config File

[pytest]
testpaths = tests

markers =
    unit: Unit tests
    integration: Integration tests

; @pytest.mark.unit
; def test_rating_distribution():

; @pytest.mark.integration
; def test_api_endpoint():

; Run only unit tests: pytest -m unit
; Or only integration tests: pytest -m integration


filterwarnings =
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning

; Suppressing this warning so i dont see it everytime i run tests
; Comes from the Startlette package I cant fix it, thats what they send me in version 1.6.0 of Starlette
; ==================================== warnings summary ==============================================
; .venv\Lib\site-packages\starlette\testclient.py:53
;   C:\Users\kwnp1\Documents\GitHubWorkFlow\MoviesSpringNextjs\MoviesSpringNextjs\analytics\.venv\Lib\site-packages\starlette\testclient.py:53: DeprecationWarning: The anyio.abc.BlockingPortal alias is deprecated, use anyio.from_thread.BlockingPortal instead.
;     _PortalFactoryType = Callable[[], AbstractContextManager[anyio.abc.BlockingPortal]]

; -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
; ==================================== 17 passed, 1 warning in 7.86s =================================