import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { hind } from "./resources/fonts";
import Footer from "./components/Footer";
import HomeCursor from "./components/HomeCursor";
import RisingBlocks from "./components/RisingBlocks";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hind.className} relative antialiased min-w-full min-h-full tracking-wide selection:bg-fuchsia-300 scroll-smooth`}
      >
        {/* cursor */}
        <HomeCursor />

        <header className="sticky top-0 z-20">
          <Navbar />
        </header>

        {children}

        <footer className="flex items-center">
          <Footer />
        </footer>

        {/*RisingBlocksAnimation  */}
        <RisingBlocks />
      </body>
    </html>
  );
}
