import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./../components/navbar/Navbar";
import { hind } from "../resources/fonts";
import Footer from "./../components/footer/Footer";
import { FavoritesProvider } from "@/context/FavoritesContext";
// import HomeCursor from "./components/cursors/HomeCursor";
// import RisingBlocks from "./components/RisingBlocks";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hind.className} relative antialiased max-w-screen min-h-screen tracking-wide selection:bg-fuchsia-300 scroll-smooth `}
      >
        <FavoritesProvider>
          {/* cursor */}
          {/* <HomeCursor /> */}

          <header className="sticky top-0 z-20">
            <Navbar />
          </header>

          <div className="relative w-full h-full bg-contrast z-10">
            {children}
          </div>

          <footer className="footBlur w-full min-h-[40vh] border-t-2 border-accent flex flex-col justify-center bg-colour text-contrast md:sticky md:bottom-0 md:z-0">
            <Footer />

            <div className="m-auto w-3/5 flex items-center justify-center text-center">
              <h1 className="text-3xl w-full h-full">
                Sticky Footer!
              </h1>
            </div>
          </footer>

          {/*RisingBlocksAnimation  */}
          {/* <RisingBlocks /> */}
        </FavoritesProvider>
      </body>
    </html>
  );
}
